name: Python Application Code Quality

on:
  push:
    branches: [$default-branch]
  pull_request:
    branches: [$default-branch]

env:
  THRESHOLD: 0.9

jobs:
  code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        id: setup_deps
        run: |
          pip3 install -upgrade pip pylint

      - name: Setup Pylint Config
        id: setup_pylint
        run: |
          cat <<EOF > setup.cfg
          disable = "all"
          enable = [
            "abstract-method",
            "arguments-differ",
            "differing-param-doc",
            "differing-type-doc",
            "invalid-overridden-method",
            "logging-fstring-interpolation",
            "missing-param-doc",
            "missing-raises-doc",
            "missing-return-doc",
            "missing-return-type-doc",
            "missing-yield-doc",
            "missing-yield-type-doc",
            "multiple-constructor-doc",
            "protected-access",
            "redundant-returns-doc",
            "redundant-yields-doc",
            "signature-differs",
            "super-init-not-called",
            "unused-argument",
            "unused-variable",
            "useless-object-inheritance"
          ]
          EOF

      - name: Pylint code quality
        id: pylint
        run: |
          pylint --rcfile setup.cfg --fail-under=${{ env.THRESHOLD }} .
